name: CI
on:
  push:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, macos-13 ]
        include:
          - os: ubuntu-latest
            platform: unknown-linux-amd64
          - os: windows-latest
            platform: windows-amd64.exe
          - os: macos-latest
            platform: apple-darwin-aarch64
          - os: macos-13
            platform: apple-darwin-amd64

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: VirtusLab/scala-cli-setup@main
        with:
          power: 'true'
          jvm: 'temurin:21'
      - run: scala-cli test .
      - run: |
          mkdir -p target
          scala-cli package  --native-image -o target/micro-maven-resolver-${{matrix.platform}} . -- --no-fallback