name: CI
on:
  pull_request:
    branches: [ '**', '!update/**', '!pr/**' ]
  push:
    branches: [ '**', '!update/**', '!pr/**' ]
    tags: [ v* ]

concurrency:
  group: ${{ github.workflow }} @ ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, macos-13 ]
        include:
          - os: ubuntu-latest
            platform: unknown-linux-amd64
          - os: windows-latest
            platform: windows-amd64.exe
          - os: macos-latest
            platform: apple-darwin-aarch64
          - os: macos-13
            platform: apple-darwin-amd64

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: VirtusLab/scala-cli-setup@main
        with:
          power: 'true'
          jvm: 'temurin:21'
      - run: scala-cli test .
      - run: |
          mkdir -p target
          scala-cli package  --native-image -o target/micro-maven-resolver-${{matrix.platform}} . -- --no-fallback
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: micro-maven-resolver-${{matrix.platform}}
          path: target/micro-maven-resolver-${{matrix.platform}}

  publish:
    name: Publish Artifacts
    needs: [ build ]
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')
    runs-on: "ubuntu-latest"
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: assets
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./assets/micro-maven-resolver-*"]'
